/**
 * @file gui/widgets/game-selection-item-widget.hpp
 */

#ifndef AR_GUI_GAMESELECTIONITEMWIDGET_H
#define AR_GUI_GAMESELECTIONITEMWIDGET_H

#include <QWidget>
#include <QFrame>
#include "core/executable-binary.hpp"

namespace ar::gui
{
    namespace Ui
    {
        class game_selection_item_widget;
    }

    /// @brief Widget showing individual game information
    class game_selection_item_widget : public QFrame
    {
    Q_OBJECT

    public:
        /**
         * @brief Default constructor
         * @param game Represented game
         * @param parent Qt's parent window
         */
        explicit game_selection_item_widget(std::unique_ptr<ar::core::executable_binary>& game,
                                            QWidget* parent = nullptr);
        ~game_selection_item_widget() override;

        /**
         * @brief Getter for the represented game
         * @return Represented game
         */
        [[nodiscard]] std::unique_ptr<ar::core::executable_binary>& get_game();

    private:
        /// @brief Game represented by this widget, const reference as it's not owned by the widget
        std::unique_ptr<ar::core::executable_binary>& _game;

        /// @brief Qt's autogenerated Ui
        Ui::game_selection_item_widget* ui;
    };
}

#endif // AR_GUI_GAMESELECTIONITEMWIDGET_H
