/**
 * @file gui/widgets/virtual-console-selection-item-widget.hpp
 */

#ifndef AR_GUI_VIRTUALCONSOLESELECTIONITEMWIDGET_HPP
#define AR_GUI_VIRTUALCONSOLESELECTIONITEMWIDGET_HPP

#include <QFrame>
#include "core/virtual-console.hpp"

namespace ar::gui
{
    namespace Ui
    {
        class virtual_console_selection_item_widget;
    }

    /// @brief Widget showing individual virtual console information
    class virtual_console_selection_item_widget : public QFrame
    {
    Q_OBJECT

    public:
        /**
         * @brief Default constructor
         * @param virtual_console Represented virtual console
         * @param parent Qt's parent window
         */
        explicit virtual_console_selection_item_widget(std::unique_ptr<ar::core::virtual_console>& virtual_console,
                                                       QWidget* parent = nullptr);
        ~virtual_console_selection_item_widget() override;

    private:
        /// @brief Virtual console represented by this widget, const reference as it's not owned by the widget
        std::unique_ptr<ar::core::virtual_console>& _virtual_console;

        /// @brief Qt's autogenerated Ui
        Ui::virtual_console_selection_item_widget* ui;
    };
}

#endif // AR_GUI_VIRTUALCONSOLESELECTIONITEMWIDGET_HPP
