#ifndef AR_GUI_GAMEPLAYWINDOW_HPP
#define AR_GUI_GAMEPLAYWINDOW_HPP

#include <QDialog>
#include <vector>
#include <memory>
#include "core/virtual-console.hpp"
#include "core/executable-binary.hpp"

namespace ar::gui
{
    namespace Ui
    {
        class gameplay_window;
    }

    // TODO: Change to MainWindow for fullscreen support

    /// @brief Window in which output from virtual console will be shown
    class gameplay_window : public QDialog
    {
    Q_OBJECT

    public:
        /**
         * @brief Default constructor
         * @param virtual_console Virtual console that will output to this window
         * @param game Game that will be played in this window
         * @param parent Parent window
         * @throws Exceptions:
         *  - std::runtime_error: Unable to initialise SDL objects
         *  - ar::core::virtual_console_error: Virtual console threw an error
         */
        gameplay_window(std::unique_ptr<ar::core::virtual_console>& virtual_console,
                        std::unique_ptr<ar::core::executable_binary>& game,
                        QWidget* parent = nullptr);
        ~gameplay_window() override;

    private:
        /// @brief Qt's autogenerated Ui
        Ui::gameplay_window* ui;
    };
}

#endif // AR_GUI_GAMEPLAYWINDOW_HPP
